version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "
    reviewers:
    - "fdo-rs/fdo-team"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "
    reviewers:
    - "fdo-rs/fdo-team"
